version: "3.8"
services:
  kafka:
    tty: true
    image: bitnami/kafka:3.6.0
    restart: "always"
    environment:
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka:9093
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
  redis:
    tty: true
    image: elestio/redis:6.0
    restart: "always"
    command: "redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}"
    volumes:
      - ./data/redis:/var/lib/redis

  clickhouse:
    tty: true
    image: clickhouse/clickhouse-server:24.1
    restart: "always"
    environment:
      - CLICKHOUSE_DB=newjitsu_metrics
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT=1
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}

  mongo:
    image: mongo
    restart: "always"
    environment:
      MONGO_INITDB_ROOT_USERNAME: default
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}

  postgres:
    image: elestio/postgres:14
    restart: "always"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - 172.17.0.1:19675:5432
  console:
    tty: true
    image: jitsucom/console:${SOFTWARE_VERSION_TAG}
    restart: "always"
    platform: linux/amd64
    extra_hosts:
      DOMAIN_TO_CHANGE: 172.17.0.1
    environment:
      ROTOR_URL: "http://rotor:3401"
      ROTOR_AUTH_KEY: ${BULKER_TOKEN:-default}
      BULKER_URL: "http://bulker:3042"
      CONSOLE_RAW_AUTH_TOKENS: ${CONSOLE_TOKEN}
      BULKER_AUTH_KEY: ${BULKER_TOKEN}
      MIT_COMPLIANT: ${MIT_COMPLIANT:-false}
      DATABASE_URL: "postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres?schema=newjitsu"
      REDIS_URL: "redis://default:${REDIS_PASSWORD}@redis:6379"
      SEED_USER_EMAIL: ${ADMIN_EMAIL}
      SEED_USER_PASSWORD: ${ADMIN_PASSWORD}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      SYNCS_ENABLED: ${SYNCS_ENABLED:-false}
      SYNCCTL_URL: "http://syncctl:3043"
      SYNCCTL_AUTH_KEY: ${SYNCCTL_TOKEN}
      GOOGLE_SCHEDULER_KEY: ${GOOGLE_SCHEDULER_KEY}
      JITSU_INGEST_PUBLIC_URL: ${JITSU_PUBLIC_URL}:19025
      JITSU_PUBLIC_URL: ${JITSU_PUBLIC_URL}
      NEXTAUTH_URL: ${JITSU_PUBLIC_URL}
      CLICKHOUSE_HOST: "clickhouse:8123"
      CLICKHOUSE_PASSWORD: "${CLICKHOUSE_PASSWORD}"
      CLICKHOUSE_DATABASE: "newjitsu_metrics"
      UPDATE_DB: "true"
    depends_on:
      - redis
      # - bulker
      - clickhouse
      - postgres
    ports:
      - "172.17.0.1:34887:3000"

  sync-catalog-init:
    tty: true
    image: curlimages/curl
    environment:
      CONSOLE_TOKEN: ${CONSOLE_TOKEN}
    command: '/bin/sh -c ''sleep 30s && curl --silent --output nul --show-error -H "Authorization: Bearer service-admin-account:${CONSOLE_TOKEN}" http://console:3000/api/admin/catalog-refresh?initial=true'''

    depends_on:
      - console

  bulker:
    tty: true
    image: jitsucom/bulker:${SOFTWARE_VERSION_TAG}
    platform: linux/amd64
    restart: "always"
    environment:
      TERM: "xterm-256color"
      BULKER_HTTP_PORT: "3042"
      BULKER_KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
      BULKER_RAW_AUTH_TOKENS: ${BULKER_TOKEN}
      BULKER_CONFIG_SOURCE: "http://console:3000/api/admin/export/bulker-connections"
      BULKER_CONFIG_SOURCE_HTTP_AUTH_TOKEN: "service-admin-account:${CONSOLE_TOKEN}"
      BULKER_CACHE_DIR: "/tmp/cache"
      REDIS_URL: "redis://default:${REDIS_PASSWORD}@redis:6379"
      BULKER_INTERNAL_TASK_LOG: '{"id":"task_log","metricsKeyPrefix":"syncs","usesBulker":true,"type":"postgres","options":{"mode":"stream"},"credentials":{"host":"postgres","port":5432,"sslMode":"disable","database":"postgres","password":"${POSTGRES_PASSWORD}","username":"postgres","defaultSchema":"newjitsu"}}'
    depends_on:
      - console
      - kafka
    ports:
      - 172.17.0.1:9773:3042

  rotor:
    tty: true
    image: jitsucom/rotor:${SOFTWARE_VERSION_TAG}
    platform: linux/amd64
    restart: "always"
    environment:
      # DISABLE_SERVICE_prisma: "true"
      # DISABLE_SERVICE_pg: "true"
      ROTOR_RAW_AUTH_TOKENS: ${BULKER_TOKEN:-default}
      BULKER_URL: "http://bulker:3042"
      BULKER_AUTH_KEY: ${BULKER_TOKEN}
      KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
      REDIS_URL: "redis://default:${REDIS_PASSWORD}@redis:6379"
      REPOSITORY_BASE_URL: "http://console:3000/api/admin/export/"
      REPOSITORY_AUTH_TOKEN: "service-admin-account:${CONSOLE_TOKEN}"
      REPOSITORY_CACHE_DIR: "/tmp/cache"
      MONGODB_URL: "mongodb://default:${MONGO_PASSWORD}@mongo/"
      CLICKHOUSE_HOST: "clickhouse:8123"
      CLICKHOUSE_PASSWORD: "${CLICKHOUSE_PASSWORD}"
      CLICKHOUSE_DATABASE: "newjitsu_metrics"
    depends_on:
      - bulker
      - console
      # - kafka
      - redis

  ingest:
    tty: true
    image: jitsucom/ingest:latest
    platform: linux/amd64
    restart: "always"
    environment:
      TERM: "xterm-256color"
      INGEST_PUBLIC_URL: ${JITSU_PUBLIC_URL}:19025
      INGEST_KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
      INGEST_RAW_AUTH_TOKENS: ${BULKER_TOKEN}
      INGEST_REPOSITORY_URL: "http://console:3000/api/admin/export/streams-with-destinations"
      INGEST_SCRIPT_ORIGIN: "http://console:3000/api/s/javascript-library"
      INGEST_REPOSITORY_AUTH_TOKEN: "service-admin-account:${CONSOLE_TOKEN}"
      INGEST_CACHE_DIR: "/tmp/cache"
      INGEST_REDIS_URL: "redis://default:${REDIS_PASSWORD}@redis:6379"
      INGEST_ROTOR_URL: "http://rotor:3401"
      INGEST_ROTOR_AUTH_KEY: ${BULKER_TOKEN:-default}
      INGEST_CLICKHOUSE_HOST: "clickhouse:9000"
      INGEST_CLICKHOUSE_PASSWORD: "${CLICKHOUSE_PASSWORD}"
      INGEST_CLICKHOUSE_DATABASE: "newjitsu_metrics"
    depends_on:
      - console
      - rotor
    ports:
      - "172.17.0.1:35210:3049"

  syncctl:
    tty: true
    image: jitsucom/syncctl:${SOFTWARE_VERSION_TAG}
    platform: linux/amd64
    restart: "always"
    environment:
      TERM: "xterm-256color"
      HTTP_PORT: "3043"
      SYNCCTL_SYNCS_ENABLED: ${SYNCS_ENABLED}
      SYNCCTL_RAW_AUTH_TOKENS: ${SYNCCTL_TOKEN}
      SYNCCTL_DATABASE_URL: "postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres?search_path=newjitsu"
      SYNCCTL_SIDECAR_DATABASE_URL: "postgresql://postgres:${POSTGRES_PASSWORD}@${EXTERNAL_DATABASE_HOST}/postgres?search_path=newjitsu"
      SYNCCTL_BULKER_URL: "https://${EXTERNAL_BULKER_HOST}"
      SYNCCTL_BULKER_AUTH_TOKEN: ${BULKER_TOKEN}
      SYNCCTL_BULKER_LOGS_CONNECTION_ID: task_log
      # SYNCCTL_KUBERNETES_CLIENT_CONFIG: "/kubeconfig"
    volumes:
      - ./data/syncctl:/etc/syncctl
      # - ./kubeconfig:/kubeconfig
    depends_on:
      - bulker
      - postgres

  pgadmin4:
    image: elestio/pgadmin:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${ADMIN_PASSWORD}
      PGADMIN_LISTEN_PORT: 8080
    ports:
      - "172.17.0.1:63528:8080"
    volumes:
      - ./servers.json:/pgadmin4/servers.json
